### Ejercicios matrices y arrays
1) Dada la siguiente matrix:
<pre>laberinto <- matrix(c(
   "O", "X", "O", "O", "O",
   "O", "X", "X", "X", "O",
   "O", "O", "O", "O", "X",
   "X", "X", "X", "O", "X",
   "O", "O", "O", "O", "O"
 ), nrow = 5, byrow = TRUE)</pre>

In [4]:
laberinto <- matrix(c(
   "O", "X", "O", "O", "O",
   "O", "X", "X", "X", "O",
   "O", "O", "O", "O", "X",
   "X", "X", "X", "O", "X",
   "O", "O", "O", "O", "O"
 ), nrow = 5, byrow = TRUE)

* Indique donde están las "X" usando la función which

In [5]:
which(laberinto=="X")

[1]  4  6  7  9 12 14 17 23 24

* Indique donde están las "X" usando la función which pero usando el parámetro arr.ind


In [6]:
which(laberinto=="X",arr.ind = TRUE)


row col
 [1,] 4   1  
 [2,] 1   2  
 [3,] 2   2  
 [4,] 4   2  
 [5,] 2   3  
 [6,] 4   3  
 [7,] 2   4  
 [8,] 3   5  
 [9,] 4   5

* Indique cuantos valores 1 hay en la matriz


In [7]:
length(which(laberinto==1))


[1] 0

* Reemplace las "X" por 1 y los "O" por 0 y convierta la matrix en una matrix numérica


In [8]:
laberinto[laberinto=="X"] <- 1
laberinto[laberinto=="O"] <- 0
laberinto <- as.numeric(laberinto)
dim(laberinto) <- c(5,5)
print(laberinto)

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    1    0    0    0
[2,]    0    1    1    1    0
[3,]    0    0    0    0    1
[4,]    1    1    1    0    1
[5,]    0    0    0    0    0


* Indique si la matrix es simétrica


In [9]:
isSymmetric(laberinto)

[1] FALSE

* Cree una nueva matrix con los valores en las filas y columnas pares 


In [10]:
laberinto_pares<-matrix(data=0,nrow=5,ncol=5)
laberinto_pares[seq(2,dim(laberinto_pares)[1],2),seq(2,dim(laberinto_pares)[2],2)] <- 1
print(laberinto_pares)

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    0    1    0    1    0
[3,]    0    0    0    0    0
[4,]    0    1    0    1    0
[5,]    0    0    0    0    0


* Indique cuantos valores 1 hay en la matriz


In [11]:
length(which(laberinto_pares==1))


[1] 4

2. Crea una matriz que represente un Sudoku. Debe estar inicializada en NA. Luego rellenar solo un 10% de las casillas con un valor entre 1 y 9 (HINT: usa la función sample). No se preocupe de que sea un esquema válido (se pueden repetir valores en una fila por ejemplo... eso ya lo haremos más adelante...)

In [12]:
sudoku <- matrix(NA,nrow = 9,ncol = 9)
sudoku[sample(length(sudoku),length(sudoku)*0.10)] <- sample(1:9,length(sudoku)*0.10,replace=T)
print(sudoku)

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [2,]   NA   NA    7   NA   NA    4   NA   NA   NA
 [3,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [4,]   NA   NA   NA   NA    7   NA   NA    4   NA
 [5,]   NA   NA    5   NA   NA   NA   NA   NA   NA
 [6,]   NA   NA    4   NA   NA   NA   NA   NA   NA
 [7,]   NA    9   NA   NA   NA   NA   NA   NA    3
 [8,]   NA   NA   NA   NA   NA   NA   NA   NA   NA
 [9,]   NA   NA   NA   NA   NA   NA   NA   NA   NA


3. Teniendo estas dos matrices:

matriz <- matrix(sample(1:9, 30,replace=TRUE), nrow=5)

mascara <- matrix(sample(c(TRUE,FALSE), 30, replace=TRUE), nrow=5)

In [13]:
matriz <- matrix(sample(1:9, 30,replace=TRUE), nrow=5)

mascara <- matrix(sample(c(TRUE,FALSE), 30, replace=TRUE), nrow=5)

* Aplique la máscara a la matrix, en donde si la posicion en la máscara es FALSE entonces el resultado es 0 y sino se mantiene su valor


In [14]:
matriz_original <- matriz
matriz[mascara == FALSE] <- 0
print(matriz)
print(matriz_original)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    5    0    0    0    0
[2,]    7    0    0    7    9    0
[3,]    0    7    3    9    2    8
[4,]    7    2    0    6    4    0
[5,]    7    2    0    3    0    0
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    5    5    1    9    4    6
[2,]    7    8    9    7    9    3
[3,]    6    7    3    9    2    8
[4,]    7    2    6    6    4    3
[5,]    7    2    8    3    7    4


* Calcule el producto de la matriz original por la matriz modificada traspuesta (NOTA: la matriz final será de 5x5)

In [15]:
ej3 <- matriz_original %*% t(matriz)
print(ej3)

     [,1] [,2] [,3] [,4] [,5]
[1,]   25  134  175  115   72
[2,]   40  179  188  143   86
[3,]   35  123  207  118   83
[4,]   10  127  118  105   71
[5,]   10  133  111   99   62


4. Crea un array 5D llamado "mi_array5D" con las siguientes características, rellénalo con números enteros consecutivos comenzando desde 1:
    - Tamaño de la primera dimensión: 2 elementos
    - Tamaño de la segunda dimensión: 3 elementos
    - Tamaño de la tercera dimensión: 4 elementos
    - Tamaño de la cuarta dimensión: 5 elementos
    - Tamaño de la quinta dimensión: 6 elementos


In [16]:
ej4 <- array(1:(2*3*4*5*6),dim=c(2,3,4,5,6))
print(length(ej4))

[1] 720


 Accede a los siguientes elementos del array:
 
- los elementos pares (analice la posicion de esos valores en las 5 dimensiones)

In [17]:
print(ej4[ej4 %% 2 == 0])
print(which(ej4 %% 2 == 0))

  [1]   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
 [19]  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
 [37]  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 [55] 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 [73] 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 [91] 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214 216
[109] 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250 252
[127] 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286 288
[145] 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322 324
[163] 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358 360
[181] 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394 396
[199] 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430 432
[217] 434 436 438 440 442 444 446 448 450 452 454 456 458 460 46

Podemos ver que como son numeros consecutivos en las posiciones absolutas del array los indices coinciden con el valor. Por tanto

 - estudiando el caso anterior muestre los elementos impares sin usar ningun tipo de condicional, igualdad o desigualdad


In [18]:
ej4[seq(1,2*3*4*5*6,2)]

[1]   1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
 [19]  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
 [37]  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 [55] 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 [73] 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 [91] 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
[109] 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
[127] 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
[145] 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
[163] 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
[181] 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
[199] 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
[217] 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
[235] 469 471 473 475 477 479 481 483 485 487 489 491 493 495 497 499 501 503
[253] 505 507 509 511 513 515 517 519 521 523 525 527 529 531 533 535 537 539
[271] 541 543 545 547 549 551 553 555 557 559 561 563 565 567 569 571 573 575
[289] 577 579 581 583 585 587 589 591 593 595 597 599 601 603 605 607 609 611
[307] 613 615 617 619 621 623 625 627 629 631 633 635 637 639 641 643 645 647
[325] 649 651 653 655 657 659 661 663 665 667 669 671 673 675 677 679 681 683
[343] 685 687 689 691 693 695 697 699 701 703 705 707 709 711 713 715 717 719

Redimensiona el array para que tenga:
- Tamaño de la primera dimensión: 6 elementos.
- Tamaño de la segunda dimensión: 5 elementos.
- Tamaño de la tercera dimensión: 4 elementos.
- Tamaño de la cuarta dimensión: 3 elementos.
- Tamaño de la quinta dimensión: 2 elementos.

In [19]:
    dim(ej4) <- c(6,5,4,3,2)
    print(ej4)

, , 1, 1, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    7   13   19   25
[2,]    2    8   14   20   26
[3,]    3    9   15   21   27
[4,]    4   10   16   22   28
[5,]    5   11   17   23   29
[6,]    6   12   18   24   30

, , 2, 1, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   31   37   43   49   55
[2,]   32   38   44   50   56
[3,]   33   39   45   51   57
[4,]   34   40   46   52   58
[5,]   35   41   47   53   59
[6,]   36   42   48   54   60

, , 3, 1, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   61   67   73   79   85
[2,]   62   68   74   80   86
[3,]   63   69   75   81   87
[4,]   64   70   76   82   88
[5,]   65   71   77   83   89
[6,]   66   72   78   84   90

, , 4, 1, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   91   97  103  109  115
[2,]   92   98  104  110  116
[3,]   93   99  105  111  117
[4,]   94  100  106  112  118
[5,]   95  101  107  113  119
[6,]   96  102  108  114  120

, , 1, 2, 1

     [,1] [,2] [,3] [,4] [,5]
[1,]  121  127  133  139  145
[2,]  122  128  134  140  146
[

5) Supongamos que tenemos un grafo no dirigido con 6 nodos etiquetados del 1 al 6, y las siguientes aristas:
    * Arista 1: (1, 2)
    * Arista 2: (1, 3)
    * Arista 3: (2, 4)
    * Arista 4: (2, 5)
    * Arista 5: (3, 6)
    * Arista 6: (4, 5)
    
    Crea una matriz de adyacencia "matriz_adyacencia" en R para representar este grafo. En una matriz de adyacencia, las filas y columnas representan los nodos, y un valor 1 indica que existe una arista entre los nodos correspondientes, mientras que un valor 0 indica la ausencia de una arista.

In [20]:
  ej5 <- matrix(0,nrow=6,ncol=6)
  ej5[1,2] <- 1
  ej5[1,3] <- 1
  ej5[2,1] <- 1
  ej5[3,1] <- 1
  ej5[2,4] <- 1
  ej5[4,2] <- 1
  ej5[2,5] <- 1
  ej5[5,2] <- 1
  ej5[3,6] <- 1
  ej5[6,3] <- 1
  ej5[4,5] <- 1
  ej5[5,4] <- 1
  print(ej5)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    1    1    0    0    0
[2,]    1    0    0    1    1    0
[3,]    1    0    0    0    0    1
[4,]    0    1    0    0    1    0
[5,]    0    1    0    1    0    0
[6,]    0    0    1    0    0    0


   * Calcula el grado del nodo 4 en el grafo. El grado de un nodo es la cantidad de aristas que inciden en él.

In [21]:
sum(ej5[4,])

[1] 2

 * Encuentra todos los nodos adyacentes del nodo 2

In [22]:
which(ej5[2,] == 1)

[1] 1 4 5

* Cuenta la cantidad de nodos que tiene una arista hacia si mismos (self-loop)

In [23]:
sum(diag(ej5))

[1] 0